### ISSUE TITLE
Email send with smtp + ssl

### ISSUE THREAD

**Issue by MrApelPro** [vbkunin/itop-docker#46]
Hi,
I try to send notifications with my smtp server but I always got error : Error: cannot connect to host; error = stream_socket_client(): Unable to connect to ssl://mail.*****:465 (Unknown error) (errno = 0 )

On my server side I see this message: 
postfix/smtps/smtpd[1320947]: connect from 111.111.111.111
postfix/smtps/smtpd[1320947]: lost connection after CONNECT from 111.111.111.111
postfix/smtps/smtpd[1320947]: disconnect from 111.111.111.111 commands=0/0

I checked it with online smtp tester tool and it could send me an email. There is my config, please help me!
	
	//	default: 'PHPMail'
	'email_transport' => 'SMTP',

	// email_transport_smtp.encryption: tls or ssl (optional)
	//	default: ''
	'email_transport_smtp.encryption' => 'ssl',

	// email_transport_smtp.host: host name or IP address (optional)
	//	default: 'localhost'
	'email_transport_smtp.host' => 'mail.*******',

	// email_transport_smtp.password: Authentication password (optional)
	//	default: ''
	'email_transport_smtp.password' => '**********',

	// email_transport_smtp.port: port number (optional)
	//	default: 25
	'email_transport_smtp.port' => '465',

	// email_transport_smtp.username: Authentication user (optional)
	//	default: ''
	'email_transport_smtp.username' => 'noreply@*******',

**Comment by vbkunin** [comment]
HI! I don't think that the problem is with the docker image itself (which is the focus of this repo).
Try to use different iTop config parameters ('tls' instead of 'ssl' for example) and enable extended logging for the SMTP server. Try to connect and send email from inside the container using a command line client.
https://www.itophub.io/wiki/page?id=latest:admin:itop_configuration_file#e

**Comment by MrApelPro** [comment]
Yes of course, this is not your fault. I know. But I hope you know itop bettet than me since documentation of itop say nothing about this issu as I see.

tls stands for smarttls and my smtp server using ssl. I tried tls also but that not work.

I do not found anything in logs of itop but i try to increase the log level and try the cli tool for smtp sent by you. Thanks.

**Comment by vbkunin** [comment]
If you are using a self-signed certificate, check that it is allowed (email_transport_smtp.allow_self_signed = true). Also try to disable a peer verification by setting email_transport_smtp.verify_peer to false. For debugging purposes, check if SMTP will work without any authentication and SSL on port 25 to find out exactly what the problem is. Make sure that asynchronous sending is disabled (email_asynchronous = false) and use the test page http://itop-server-location/setup/email.test.php.

**Comment by MrApelPro** [comment]
Thanks for your help. I look for these params but do not found.. than chatgpt said verify and selfsigned keys are under options array so i try it but not working.. thanks x 1000 for you, this was simplier than i thought...

But email sending fault with the same errors and my smtp log does not contains any new information. I cannot try the smtp send with cli tool from container and the 25 port with pure config, but I do it as soon as i can.

With this params found I think the problem maybe around docker container or the firewall above it.. But I get closer when I try the cli tool.. 

Thanks a lot!

**Comment by MrApelPro** [comment]
Hi!

The problem was because certificate generated with other domain than my mail server - my VPS provider give me his own domain and set the PTR record and I think thats because the certificate holds that domain and not mine. I changed the host param to the domain which is in the domain and it works now.

I do not understand why this keys (verify_peer etc) do nothing with it, but I can send notification after all. Thank you so much for your help!
